// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SomeWeirdApplicationBackend.Infrastructure;

namespace SomeWeirdApplicationBackend.Migrations
{
    [DbContext(typeof(BankingContext))]
    [Migration("20190903143849_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.card_hilo", "'card_hilo', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SomeWeirdApplicationBackend.Models.Bank.Card", b =>
                {
                    b.Property<int>("CardInternalId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:HiLoSequenceName", "card_hilo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("CVV")
                        .IsRequired();

                    b.Property<DateTime>("ExpirationDate")
                        .HasMaxLength(100);

                    b.Property<string>("HolderName");

                    b.Property<string>("Number")
                        .IsRequired();

                    b.Property<int>("Type");

                    b.Property<int>("TypeId");

                    b.Property<int>("UserId");

                    b.HasKey("CardInternalId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("SomeWeirdApplicationBackend.Models.Bank.MoneyMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int>("CardInternalId");

                    b.Property<DateTime>("MovementTime")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("MoneyMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
