version: '3.4'

services:
  some-weird-application-backend:
    image: some-weird-application-backend
    build:
      context: .
      dockerfile: SomeWeirdApplicationBackend/Dockerfile
    depends_on:
      - sql.data

  some-weird-application-frontend:
    image: some-weird-application-frontend
    build:
      context: some-weird-application-frontend
      dockerfile: Dockerfile   
    depends_on:
      - some-weird-application-backend

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

