// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SomeWeirdApplicationBackend.Infrastructure;

namespace SomeWeirdApplicationBackend.Migrations.WebSite
{
    [DbContext(typeof(WebSiteContext))]
    partial class WebSiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SomeWeirdApplicationBackend.Models.WebCrawler.WebSiteStatistics", b =>
                {
                    b.Property<int>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Occurrences");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.Property<int?>("WebSiteStatisticsInternalId");

                    b.HasKey("InternalId");

                    b.HasIndex("WebSiteStatisticsInternalId");

                    b.ToTable("WebSites");
                });

            modelBuilder.Entity("SomeWeirdApplicationBackend.Models.WebCrawler.WebSiteStatistics", b =>
                {
                    b.HasOne("SomeWeirdApplicationBackend.Models.WebCrawler.WebSiteStatistics")
                        .WithMany("LinkedSites")
                        .HasForeignKey("WebSiteStatisticsInternalId");
                });
#pragma warning restore 612, 618
        }
    }
}
